import json
from pathlib import Path

import streamlit as st


BASE_DIR = Path(__file__).resolve().parent
ASSETS_DIR = BASE_DIR / "assets"

ASSETS = {
    "Training Curves": ASSETS_DIR / "training_comparison.png",
    "Custom CNN Confusion Matrix": ASSETS_DIR / "custom_cnn_confusion_matrix.png",
    "ResNet18 Confusion Matrix": ASSETS_DIR / "resnet18_confusion_matrix.png",
    "Sample Predictions": ASSETS_DIR / "sample_predictions.png",
}


def load_results(path: Path) -> dict:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {}


def save_results(path: Path, data: dict) -> None:
    path.write_text(json.dumps(data, indent=2), encoding="utf-8")


def main() -> None:
    st.set_page_config(
        page_title="CIFAR-10 CNN Results",
        page_icon=":chart_with_upwards_trend:",
        layout="wide",
    )

    st.title("CIFAR-10 Classification Results")
    st.write(
        "This report summarizes training runs for a custom CNN and a ResNet18 "
        "transfer learning model on CIFAR-10."
    )

    results_path = BASE_DIR / "results.json"
    results = load_results(results_path)

    with st.sidebar:
        st.header("Results.json")
        st.write("Add metrics here to show them in the header.")
        custom_best = st.text_input(
            "Custom CNN Best Accuracy",
            value=results.get("custom_best_acc", ""),
        )
        custom_time = st.text_input(
            "Custom CNN Training Time (min)",
            value=results.get("custom_time_min", ""),
        )
        resnet_best = st.text_input(
            "ResNet18 Best Accuracy",
            value=results.get("resnet_best_acc", ""),
        )
        resnet_time = st.text_input(
            "ResNet18 Training Time (min)",
            value=results.get("resnet_time_min", ""),
        )
        if st.button("Save results.json"):
            save_results(
                results_path,
                {
                    "custom_best_acc": custom_best,
                    "custom_time_min": custom_time,
                    "resnet_best_acc": resnet_best,
                    "resnet_time_min": resnet_time,
                },
            )
            st.success("Saved results.json")

    col1, col2, col3 = st.columns(3)
    with col1:
        st.subheader("Custom CNN")
        st.metric(
            "Best Test Accuracy",
            results.get("custom_best_acc", "N/A"),
        )
        st.metric(
            "Training Time (min)",
            results.get("custom_time_min", "N/A"),
        )
    with col2:
        st.subheader("ResNet18")
        st.metric(
            "Best Test Accuracy",
            results.get("resnet_best_acc", "N/A"),
        )
        st.metric(
            "Training Time (min)",
            results.get("resnet_time_min", "N/A"),
        )
    with col3:
        st.subheader("Summary")
        st.write(
            "The custom CNN is smaller and achieved higher accuracy in this run. "
            "ResNet18 trained faster but scored slightly lower."
        )

    st.divider()
    st.header("Visualizations")
    st.write(
        "Images below are generated by `cnn_classifier.py`. "
        "Run training first to produce them."
    )

    for title, path in ASSETS.items():
        if path.exists():
            st.subheader(title)
            st.image(str(path), use_container_width=True)
        else:
            st.warning(f"Missing: {path.name}. Run training to generate it.")

    st.divider()
    st.header("What This Shows")
    st.write(
        "- Training curves compare convergence behavior of both models.\n"
        "- Confusion matrices show where each model confuses classes.\n"
        "- Sample predictions visualize correct vs. incorrect examples."
    )



if __name__ == "__main__":
    main()

